#!/bin/sh
#cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
#. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wclean  specie
wclean  solidSpecie
wclean  thermophysicalProperties

wclean  basic
wclean  reactionThermo
wclean  laminarFlameSpeed
wclean  chemistryModel
wclean  barotropicCompressibilityModel
wclean  SLGThermo


wclean  solidThermo
wclean  solidChemistryModel

wclean  radiation

#------------------------------------------------------------------------------
