# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_VLE')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_VLE')
    _VLE = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_VLE', [dirname(__file__)])
        except ImportError:
            import _VLE
            return _VLE
        try:
            _mod = imp.load_module('_VLE', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _VLE = swig_import_helper()
    del swig_import_helper
else:
    import _VLE
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _VLE.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _VLE.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _VLE.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _VLE.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _VLE.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _VLE.SwigPyIterator_equal(self, x)

    def copy(self):
        return _VLE.SwigPyIterator_copy(self)

    def next(self):
        return _VLE.SwigPyIterator_next(self)

    def __next__(self):
        return _VLE.SwigPyIterator___next__(self)

    def previous(self):
        return _VLE.SwigPyIterator_previous(self)

    def advance(self, n):
        return _VLE.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _VLE.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _VLE.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _VLE.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _VLE.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _VLE.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _VLE.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _VLE.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _VLE.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _VLE.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _VLE.DoubleVector___bool__(self)

    def __len__(self):
        return _VLE.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _VLE.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _VLE.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _VLE.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _VLE.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _VLE.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _VLE.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _VLE.DoubleVector_pop(self)

    def append(self, x):
        return _VLE.DoubleVector_append(self, x)

    def empty(self):
        return _VLE.DoubleVector_empty(self)

    def size(self):
        return _VLE.DoubleVector_size(self)

    def swap(self, v):
        return _VLE.DoubleVector_swap(self, v)

    def begin(self):
        return _VLE.DoubleVector_begin(self)

    def end(self):
        return _VLE.DoubleVector_end(self)

    def rbegin(self):
        return _VLE.DoubleVector_rbegin(self)

    def rend(self):
        return _VLE.DoubleVector_rend(self)

    def clear(self):
        return _VLE.DoubleVector_clear(self)

    def get_allocator(self):
        return _VLE.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _VLE.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _VLE.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _VLE.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _VLE.DoubleVector_push_back(self, x)

    def front(self):
        return _VLE.DoubleVector_front(self)

    def back(self):
        return _VLE.DoubleVector_back(self)

    def assign(self, n, x):
        return _VLE.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _VLE.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _VLE.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _VLE.DoubleVector_reserve(self, n)

    def capacity(self):
        return _VLE.DoubleVector_capacity(self)
    __swig_destroy__ = _VLE.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _VLE.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _VLE.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _VLE.StringVector___nonzero__(self)

    def __bool__(self):
        return _VLE.StringVector___bool__(self)

    def __len__(self):
        return _VLE.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _VLE.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _VLE.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _VLE.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _VLE.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _VLE.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _VLE.StringVector___setitem__(self, *args)

    def pop(self):
        return _VLE.StringVector_pop(self)

    def append(self, x):
        return _VLE.StringVector_append(self, x)

    def empty(self):
        return _VLE.StringVector_empty(self)

    def size(self):
        return _VLE.StringVector_size(self)

    def swap(self, v):
        return _VLE.StringVector_swap(self, v)

    def begin(self):
        return _VLE.StringVector_begin(self)

    def end(self):
        return _VLE.StringVector_end(self)

    def rbegin(self):
        return _VLE.StringVector_rbegin(self)

    def rend(self):
        return _VLE.StringVector_rend(self)

    def clear(self):
        return _VLE.StringVector_clear(self)

    def get_allocator(self):
        return _VLE.StringVector_get_allocator(self)

    def pop_back(self):
        return _VLE.StringVector_pop_back(self)

    def erase(self, *args):
        return _VLE.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _VLE.new_StringVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _VLE.StringVector_push_back(self, x)

    def front(self):
        return _VLE.StringVector_front(self)

    def back(self):
        return _VLE.StringVector_back(self)

    def assign(self, n, x):
        return _VLE.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _VLE.StringVector_resize(self, *args)

    def insert(self, *args):
        return _VLE.StringVector_insert(self, *args)

    def reserve(self, n):
        return _VLE.StringVector_reserve(self, n)

    def capacity(self):
        return _VLE.StringVector_capacity(self)
    __swig_destroy__ = _VLE.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _VLE.StringVector_swigregister
StringVector_swigregister(StringVector)

class solver(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, solver, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, solver, name)
    __repr__ = _swig_repr
    __swig_setmethods__["path"] = _VLE.solver_path_set
    __swig_getmethods__["path"] = _VLE.solver_path_get
    if _newclass:
        path = _swig_property(_VLE.solver_path_get, _VLE.solver_path_set)
    __swig_setmethods__["P"] = _VLE.solver_P_set
    __swig_getmethods__["P"] = _VLE.solver_P_get
    if _newclass:
        P = _swig_property(_VLE.solver_P_get, _VLE.solver_P_set)
    __swig_setmethods__["T"] = _VLE.solver_T_set
    __swig_getmethods__["T"] = _VLE.solver_T_get
    if _newclass:
        T = _swig_property(_VLE.solver_T_get, _VLE.solver_T_set)
    __swig_setmethods__["X"] = _VLE.solver_X_set
    __swig_getmethods__["X"] = _VLE.solver_X_get
    if _newclass:
        X = _swig_property(_VLE.solver_X_get, _VLE.solver_X_set)
    __swig_setmethods__["specie"] = _VLE.solver_specie_set
    __swig_getmethods__["specie"] = _VLE.solver_specie_get
    if _newclass:
        specie = _swig_property(_VLE.solver_specie_get, _VLE.solver_specie_set)
    __swig_setmethods__["s"] = _VLE.solver_s_set
    __swig_getmethods__["s"] = _VLE.solver_s_get
    if _newclass:
        s = _swig_property(_VLE.solver_s_get, _VLE.solver_s_set)
    __swig_setmethods__["dict"] = _VLE.solver_dict_set
    __swig_getmethods__["dict"] = _VLE.solver_dict_get
    if _newclass:
        dict = _swig_property(_VLE.solver_dict_get, _VLE.solver_dict_set)

    def update(self):
        return _VLE.solver_update(self)
    __swig_setmethods__["PR"] = _VLE.solver_PR_set
    __swig_getmethods__["PR"] = _VLE.solver_PR_get
    if _newclass:
        PR = _swig_property(_VLE.solver_PR_get, _VLE.solver_PR_set)

    def __init__(self, arg2):
        this = _VLE.new_solver(arg2)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _VLE.delete_solver
    __del__ = lambda self: None

    def solve(self, flag):
        return _VLE.solver_solve(self, flag)
    __swig_setmethods__["vaporfra"] = _VLE.solver_vaporfra_set
    __swig_getmethods__["vaporfra"] = _VLE.solver_vaporfra_get
    if _newclass:
        vaporfra = _swig_property(_VLE.solver_vaporfra_get, _VLE.solver_vaporfra_set)

    def density(self):
        return _VLE.solver_density(self)

    def Z(self):
        return _VLE.solver_Z(self)

    def twophase(self, rho, lt, rt):
        return _VLE.solver_twophase(self, rho, lt, rt)
    __swig_setmethods__["equalconstant"] = _VLE.solver_equalconstant_set
    __swig_getmethods__["equalconstant"] = _VLE.solver_equalconstant_get
    if _newclass:
        equalconstant = _swig_property(_VLE.solver_equalconstant_get, _VLE.solver_equalconstant_set)
    __swig_setmethods__["comp_liq"] = _VLE.solver_comp_liq_set
    __swig_getmethods__["comp_liq"] = _VLE.solver_comp_liq_get
    if _newclass:
        comp_liq = _swig_property(_VLE.solver_comp_liq_get, _VLE.solver_comp_liq_set)
    __swig_setmethods__["comp_gas"] = _VLE.solver_comp_gas_set
    __swig_getmethods__["comp_gas"] = _VLE.solver_comp_gas_get
    if _newclass:
        comp_gas = _swig_property(_VLE.solver_comp_gas_get, _VLE.solver_comp_gas_set)
solver_swigregister = _VLE.solver_swigregister
solver_swigregister(solver)

# This file is compatible with both classic and new-style classes.


